all:	achachaves codifica decodifica achaparametros

achachaves:
	gcc -o achachaves achachaves.c

codifica:
	gcc -o codifica codifica.c

decodifica:
	gcc -o decodifica decodifica.c

achaparametros:
	gcc -o achaparametros achaparametros.c

clean:
	rm -rf achachaves codifica decodifica achaparametros	
